In [36]:
from sklearn.linear_model import LinearRegression 
import numpy as np 

In [37]:
X = np.array([[0, 0],
                [1, 1],
                [2, 2],
                [3, 3],
                [4, 4]])


In [38]:
y = np.array([0, 1, 2, 3, 4 ])

In [39]:
model = LinearRegression()

In [40]:
model.fit(X, y)

LinearRegression()

In [41]:
model.predict([[1, 2]])

array([1.5])

In [42]:
model.coef_

array([0.5, 0.5])

In [43]:
model.intercept_

np.float64(0.0)

In [44]:
A = np.concatenate((np.ones(shape=(len(X), 1)), X), axis= 1)
A

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 3., 3.],
       [1., 4., 4.]])

In [45]:
np.linalg.det(A.T @ A)

np.float64(0.0)

In [46]:
U, S, Vh = np.linalg.svd(A, full_matrices=False)

In [47]:
U

array([[ 0.02954199,  0.77403312, -0.41491169],
       [ 0.20213602,  0.50905897,  0.06722474],
       [ 0.37473004,  0.24408481,  0.83770511],
       [ 0.54732407, -0.02088934, -0.21743768],
       [ 0.71991809, -0.28586349, -0.27258048]])

In [48]:
S

array([7.96387419, 1.25567026, 0.        ])

In [49]:
Vh 

array([[ 0.23526868,  0.68725856,  0.68725856],
       [ 0.97193037, -0.16636008, -0.16636008],
       [ 0.        , -0.70710678,  0.70710678]])

In [50]:
V = Vh.T
V

array([[ 0.23526868,  0.97193037,  0.        ],
       [ 0.68725856, -0.16636008, -0.70710678],
       [ 0.68725856, -0.16636008,  0.70710678]])

In [51]:
S_inv = [1/s if s > 1e-6 else 0 for s in S ]
S_inv

[np.float64(0.12556702623967594), np.float64(0.7963874194896131), 0]

In [52]:
V @ np.diag(S_inv) @ U.T @ y

array([-1.66533454e-15,  5.00000000e-01,  5.00000000e-01])

In [59]:
f = lambda w: 1/ len(X) * np.linalg.norm(A @ w - y) ** 2

In [60]:
g = lambda w: 1 / len(X) * 2 * A.T @ (A @ w - y)

In [61]:
lr = 0.001
k = 0
w = np.array([[0], [0], [0]])
while k < 1_000:
    k += 1
    w = w - lr * g(w)
    e = np.linalg.norm(g(w))
    if k < 1e-3:
        print('*', k, w, e, f(w))
        break 
    print(k, w, e, f(w))

1 [[0.    0.002 0.004 0.006 0.008]
 [0.    0.004 0.008 0.012 0.016]
 [0.    0.004 0.008 0.012 0.016]] 32.038224669915785 28.933559999999996
2 [[0.       0.003964 0.007928 0.011892 0.015856]
 [0.       0.007896 0.015792 0.023688 0.031584]
 [0.       0.007896 0.015792 0.023688 0.031584]] 31.234238953630364 27.91999304496001
3 [[0.         0.0058929  0.01178581 0.01767871 0.02357162]
 [0.         0.01169064 0.02338128 0.03507192 0.04676256]
 [0.         0.01169064 0.02338128 0.03507192 0.04676256]] 30.4508649283938 26.95665115193796
4 [[0.         0.00778759 0.01557519 0.02336278 0.03115037]
 [0.         0.01538649 0.03077299 0.04615948 0.06154597]
 [0.         0.01538649 0.03077299 0.04615948 0.06154597]] 29.68758481164367 26.041018987905787
5 [[0.         0.00964893 0.01929785 0.02894678 0.0385957 ]
 [0.         0.01898607 0.03797213 0.0569582  0.07594427]
 [0.         0.01898607 0.03797213 0.0569582  0.07594427]] 28.94389406820247 25.17070722464877
6 [[0.         0.01147774 0.02295548 